Add ADR for transformer architecture
edx/event-routing-backends pull request #10
Opened 2020-10-22 12:33 UTC by danialmalik

**Description:** 
Add ADR for decision about developing Transformers as "Processors"

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2020-10-22 12:33 UTC, edx-webhook commented
Thanks for the pull request, @danialmalik! I've created [OSPR-5076](https://openedx.atlassian.net/browse/OSPR-5076) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2020-10-22 14:43 UTC, feanil requested changes
One change then I think this is good to go.

2020-10-22 14:43 UTC, feanil commented on docs/decisions/0004-transformers-architecture.md
> +Transformers will be developed as event transformers that can be added in
```suggestion
Transformers will be developed as event processors that can be added in
```

2020-10-22 17:45 UTC, danialmalik commented on docs/decisions/0004-transformers-architecture.md
> +Transformers will be developed as event transformers that can be added in
My bad. Updated now :+1:

2020-10-23 02:34 UTC, natabene commented
@danialmalik Thank you for your contribution!

2021-01-12 21:11 UTC, natabene commented
@feanil Could you review this?

2021-01-15 14:24 UTC, feanil approved these changes

2021-01-15 14:24 UTC, merged

2021-01-15 14:24 UTC, edx-webhook commented
@danialmalik 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/event-routing-backends&entry.867055334=https://github.com/edx/event-routing-backends/pull/10&entry.1484655318=https://github.com/danialmalik&entry.752974735=2020-10-22+12:33&entry.1917517419=2021-01-15+14:24&entry.2133058324=Yes) so we can improve your experience in the future.